import type { Metadata } from 'next';
import { Oswald, JetBrains_Mono, Rajdhani } from 'next/font/google';
import './globals.css';
import Providers from '@/providers/providers';

const oswald = Oswald({
	variable: '--font-oswald',
	subsets: ['latin'],
});

const jetbrainsMono = JetBrains_Mono({
	variable: '--font-jetbrains-mono',
	subsets: ['latin'],
});

const rajdhani = Rajdhani({
	variable: '--font-rajdhani',
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			suppressHydrationWarning
			lang="en"
			className={`${oswald.variable} ${jetbrainsMono.variable} ${rajdhani.variable} h-full antialiased`}
		>
			<body className="min-h-full flex flex-col">
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
